-- hypeForge: the theme reaches the parts of the desktop Noctalia does not draw (D-36, D-40).
-- Noctalia, the desktop shell, owns the theme choice: its bar, panels, launcher, notifications
-- and wallpaper follow its palette. After every palette change its hook (bin/hypeforge-theme-sync)
-- writes the theme's id to ~/.config/hypeforge/theme and reloads Hyprland, which runs this file:
-- window borders, title bars, the terminal, GTK apps, Hyprland's own apps and the lock screen.
--   one of our five (themes/<id>.lua): our exact, hand-picked colours
--   "noctalia" (any other Noctalia palette): the colours Noctalia fills into noctalia-colours.lua
-- Load this before titlebars.lua, which reads the colours from HYPEFORGE_THEME.
-- Win + Alt + T (next theme) is bin/hypeforge-theme-next.
-- The idea of one colour file per theme that every app follows comes from Omarchy, with thanks.

local HOME = os.getenv("HOME")
local HF = HOME .. "/.config/hypeforge"
local DIR = HF .. "/hypr/themes/"
local CURRENT = HF .. "/theme"
local ALACRITTY = HOME .. "/.config/alacritty/themes/hypeforge-current.toml"
local ORDER = { "mocha", "black", "green", "gray", "white" }

local function read_current()
    local f = io.open(CURRENT, "r")
    local id = f and f:read("*l") or "mocha"
    if f then f:close() end
    if id == "noctalia" then return id end
    for _, known in ipairs(ORDER) do if known == id then return id end end
    return "mocha"
end

local function load_theme(id)
    local file = id == "noctalia" and (HF .. "/hypr/noctalia-colours.lua") or (DIR .. id .. ".lua")
    local ok, t = pcall(dofile, file)
    if ok and type(t) == "table" and t.c then t.id = id; return t end
    return nil
end

local id = read_current()
local T = load_theme(id) or load_theme("mocha")
HYPEFORGE_THEME = T

local function rgba(hex, alpha) return "rgba(" .. hex:sub(2) .. (alpha or "ff") .. ")" end

-- Window borders.
hl.config({
    general = {
        col = {
            active_border = rgba(T.c.border),
            inactive_border = rgba(T.c.inactive),
        },
    },
})

-- Alacritty's colours: the theme's hand-picked 16 colours (themes/terminal.lua, F-12),
-- written to hypeforge-current.toml, which Alacritty imports and re-reads when it changes.
-- Every theme's palette is also saved as hypeforge-<id>.toml, so alacrittyForge's Themes
-- section lists them. Picking hypeforge-current there means "follow the desktop"; picking
-- anything else keeps that theme for the terminal only.
local TERMINAL = (function()
    local ok, p = pcall(dofile, DIR .. "terminal.lua")
    return ok and p or {}
end)()
local ALACRITTY_DIR = HOME .. "/.config/alacritty/themes/"
local function alacritty_toml(t, id)
    local p, c = TERMINAL[id] or t.terminal, t.c
    if not p then return nil end
    local names = { "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white" }
    local out = { "# Generated by hypeForge: the " .. t.name .. " theme's terminal colours (D-36, F-12).",
                  "# Do not edit; it is rewritten from themes/terminal.lua.", "",
                  "[colors.primary]", 'background = "' .. p.bg .. '"', 'foreground = "' .. p.fg .. '"', "",
                  "[colors.cursor]", 'cursor = "' .. c.accent .. '"', 'text = "' .. p.bg .. '"', "",
                  "[colors.selection]", 'background = "' .. c.selection .. '"', 'text = "' .. p.fg .. '"' }
    for _, part in ipairs({ "normal", "bright" }) do
        out[#out + 1] = ""
        out[#out + 1] = "[colors." .. part .. "]"
        for i, n in ipairs(names) do out[#out + 1] = n .. ' = "' .. p[part][i] .. '"' end
    end
    return table.concat(out, "\n") .. "\n"
end
local function write_alacritty(t)
    local toml = alacritty_toml(t, t.id)
    if not toml then return end
    local old = io.open(ALACRITTY, "r")
    local same = old and old:read("*a") == toml
    if old then old:close() end
    if not same then
        local f = io.open(ALACRITTY, "w")
        if f then f:write(toml); f:close() end
    end
    for _, id in ipairs(ORDER) do                      -- the named copies, for alacrittyForge
        local other = load_theme(id)
        local named = other and alacritty_toml(other, id)
        if named then
            local f = io.open(ALACRITTY_DIR .. "hypeforge-" .. id .. ".toml", "w")
            if f then f:write(named); f:close() end
        end
    end
end
write_alacritty(T)

-- GTK apps (and Chromium's window frame): adw-gtk-theme reads these named colours from
-- gtk.css (D-21); light or dark follows the theme's kind.
local function write_file_if_changed(path, text)
    local old = io.open(path, "r")
    local same = old and old:read("*a") == text
    if old then old:close() end
    if same then return false end
    os.execute('mkdir -p "' .. path:match("(.*)/") .. '"')
    local f = io.open(path, "w")
    if f then f:write(text); f:close() end
    return true
end

local function write_gtk(t)
    local c, dark = t.c, t.kind == "dark"
    local on_accent = dark and c.window or "#ffffff"
    local defs = {
        { "accent_color", c.accent }, { "accent_bg_color", c.accent }, { "accent_fg_color", on_accent },
        { "window_bg_color", c.window }, { "window_fg_color", c.text },
        { "view_bg_color", c.window }, { "view_fg_color", c.text },
        { "headerbar_bg_color", c.titlebar }, { "headerbar_fg_color", c.text },
        { "headerbar_backdrop_color", c.titlebar },
        { "sidebar_bg_color", c.titlebar }, { "sidebar_fg_color", c.text },
        { "card_bg_color", c.selection }, { "card_fg_color", c.text },
        { "popover_bg_color", c.titlebar }, { "popover_fg_color", c.text },
        { "dialog_bg_color", c.titlebar }, { "dialog_fg_color", c.text },
        { "destructive_bg_color", c.red }, { "success_bg_color", c.green },
    }
    local lines = { "/* Generated by hypeForge from the " .. t.name .. " theme (D-36). Rewritten on every theme change. */" }
    for _, d in ipairs(defs) do lines[#lines + 1] = "@define-color " .. d[1] .. " " .. d[2] .. ";" end
    local css = table.concat(lines, "\n") .. "\n"
    local changed = write_file_if_changed(HOME .. "/.config/gtk-3.0/gtk.css", css)
    changed = write_file_if_changed(HOME .. "/.config/gtk-4.0/gtk.css", css) or changed
    if changed then
        local gtk = dark and "adw-gtk3-dark" or "adw-gtk3"
        hl.dispatch(hl.dsp.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme " .. gtk))
        hl.dispatch(hl.dsp.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme " ..
            (dark and "prefer-dark" or "prefer-light")))
    end
end
write_gtk(T)

-- Chromium's frame colour is a system policy file, outside $HOME. It waits for hypeForge's
-- own single-purpose helper, with a backup (D-8); until then browsers keep their own colour.

-- The lock screen (hyprlock, which stays: Javier, 2026-09-30) reads named colours from a file.
local function write_lock(t)
    local c = t.c
    local names = { "bar", "barText", "accent", "border", "inactive", "window", "text", "subtext",
                    "selection", "green", "red", "a3" }
    local lock = { "# Generated by hypeForge from the " .. t.name .. " theme (D-36)." }
    for _, n in ipairs(names) do
        lock[#lock + 1] = "$" .. n .. " = rgb(" .. c[n]:sub(2) .. ")"
    end
    write_file_if_changed(HF .. "/hypr/hyprlock-colours.conf", table.concat(lock, "\n") .. "\n")
end
write_lock(T)

-- Hyprland's own apps (the password pop-up, the guiutils windows) all read one file, hyprtoolkit.conf, and re-read it as soon as it
-- changes (D-39: Hyprland's own apps first). Fonts: 12 is the standard (F-7).
local function write_hyprtoolkit(t)
    local c = t.c
    local function argb(hex) return "0xFF" .. hex:sub(2):upper() end
    local conf = table.concat({
        "# Generated by hypeForge from the " .. t.name .. " theme (D-36). Rewritten on every theme change.",
        "background = " .. argb(c.window),
        "base = " .. argb(c.titlebar),
        "alternate_base = " .. argb(c.selection),
        "text = " .. argb(c.text),
        "bright_text = " .. argb(c.text),
        "link_text = " .. argb(c.a4),
        "accent = " .. argb(c.accent),
        "accent_secondary = " .. argb(c.border),
        "rounding_large = 10",
        "rounding_small = 6",
        "h1_size = 20", "h2_size = 16", "h3_size = 14",
        "font_size = 12", "small_font_size = 11",
        "font_family = Noto Sans",
        "font_family_monospace = JetBrainsMono Nerd Font",
        "icon_theme = candy-icons",
    }, "\n") .. "\n"
    write_file_if_changed(HF .. "/hypr/hyprtoolkit.conf", conf)
end
write_hyprtoolkit(T)
