# hypeForge lock screen (hyprlock, D-20). Colours: hyprlock-colours.conf, written by the theme.
source = ~/.config/hypeforge/hypr/hyprlock-colours.conf

general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    brightness = 0.6
}

input-field {
    monitor =
    size = 320, 52
    outline_thickness = 2
    outer_color = $accent
    inner_color = $window
    font_color = $text
    check_color = $green
    fail_color = $red
    fade_on_empty = false
    rounding = 10
    font_family = JetBrainsMono Nerd Font
    placeholder_text = Password
    fail_text = $PAMFAIL
    dots_spacing = 0.3
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = $text
    font_size = 84
    font_family = JetBrainsMono Nerd Font
    position = 0, 140
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = $subtext
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 60
    halign = center
    valign = center
}
