-- Generated by Noctalia from the active palette (D-40). Do not edit: rewritten on every theme change.
-- theme.lua reads it when the palette is not one of hypeForge's five.
return {
    name = "Noctalia",
    kind = "{{ mode }}",
    c = {
        accent = "{{ colors.primary.default.hex }}",
        border = "{{ colors.secondary.default.hex }}",
        inactive = "{{ colors.surface_variant.default.hex }}",
        titlebar = "{{ colors.surface_dim.default.hex }}",
        bar = "{{ colors.surface_container_low.default.hex }}",
        barText = "{{ colors.on_surface.default.hex }}",
        window = "{{ colors.surface.default.hex }}",
        text = "{{ colors.on_surface.default.hex }}",
        subtext = "{{ colors.on_surface_variant.default.hex }}",
        selection = "{{ colors.surface_variant.default.hex }}",
        red = "{{ colors.error.default.hex }}",
        btnIcon = "{{ colors.on_primary.default.hex }}",
        green = "{{ colors.terminal_normal_green.default.hex }}",
        a1 = "{{ colors.terminal_normal_red.default.hex }}",
        a2 = "{{ colors.terminal_normal_green.default.hex }}",
        a3 = "{{ colors.terminal_normal_yellow.default.hex }}",
        a4 = "{{ colors.terminal_normal_blue.default.hex }}",
        a5 = "{{ colors.terminal_normal_magenta.default.hex }}",
        a6 = "{{ colors.terminal_normal_cyan.default.hex }}",
    },
    terminal = {
        bg = "{{ colors.terminal_background.default.hex }}", fg = "{{ colors.terminal_foreground.default.hex }}",
        normal = { "{{ colors.terminal_normal_black.default.hex }}", "{{ colors.terminal_normal_red.default.hex }}", "{{ colors.terminal_normal_green.default.hex }}", "{{ colors.terminal_normal_yellow.default.hex }}", "{{ colors.terminal_normal_blue.default.hex }}", "{{ colors.terminal_normal_magenta.default.hex }}", "{{ colors.terminal_normal_cyan.default.hex }}", "{{ colors.terminal_normal_white.default.hex }}", },
        bright = { "{{ colors.terminal_bright_black.default.hex }}", "{{ colors.terminal_bright_red.default.hex }}", "{{ colors.terminal_bright_green.default.hex }}", "{{ colors.terminal_bright_yellow.default.hex }}", "{{ colors.terminal_bright_blue.default.hex }}", "{{ colors.terminal_bright_magenta.default.hex }}", "{{ colors.terminal_bright_cyan.default.hex }}", "{{ colors.terminal_bright_white.default.hex }}", },
    },
}
