-- hypeForge prototype: one colour file per theme drives the desktop (D-36).
-- The five themes live in hypeforge-themes/<id>.lua next to this file; the chosen one is
-- named in hypeforge-theme-current. Load this before hypeforge-titlebars.lua, which reads
-- the colours from HYPEFORGE_THEME.
--   Win + Alt + T   next theme: Mocha → Black → Green → Gray → White → Mocha
-- The idea of one colour file per theme that every app follows comes from Omarchy, with thanks.

local HOME = os.getenv("HOME")
local DIR = HOME .. "/.config/hypr/hypeforge-themes/"
local CURRENT = HOME .. "/.config/hypr/hypeforge-theme-current"
local ALACRITTY = HOME .. "/.config/alacritty/themes/hypeforge-current.toml"
local ORDER = { "mocha", "black", "green", "gray", "white" }

local function read_current()
    local f = io.open(CURRENT, "r")
    local id = f and f:read("*l") or "mocha"
    if f then f:close() end
    for _, known in ipairs(ORDER) do if known == id then return id end end
    return "mocha"
end

local function load_theme(id)
    local ok, t = pcall(dofile, DIR .. id .. ".lua")
    if ok and type(t) == "table" and t.c then t.id = id; return t end
    return nil
end

local id = read_current()
local T = load_theme(id) or load_theme("mocha")
HYPEFORGE_THEME = T

local function rgba(hex, alpha) return "rgba(" .. hex:sub(2) .. (alpha or "ff") .. ")" end

-- Window borders.
hl.config({
    general = {
        col = {
            active_border = rgba(T.c.border),
            inactive_border = rgba(T.c.inactive),
        },
    },
})

-- Alacritty's colours: written to a file Alacritty imports; it repaints when the file changes.
local function write_alacritty(t)
    local c = t.c
    local toml = string.format([[
# Generated by hypeForge from the %s theme (D-36). Do not edit; it is rewritten on every theme change.
[colors.primary]
background = "%s"
foreground = "%s"

[colors.cursor]
cursor = "%s"
text = "%s"

[colors.selection]
background = "%s"
text = "%s"

[colors.normal]
black = "%s"
red = "%s"
green = "%s"
yellow = "%s"
blue = "%s"
magenta = "%s"
cyan = "%s"
white = "%s"

[colors.bright]
black = "%s"
red = "%s"
green = "%s"
yellow = "%s"
blue = "%s"
magenta = "%s"
cyan = "%s"
white = "%s"
]], t.name, c.window, c.text, c.accent, c.window, c.selection, c.text,
        c.selection, c.a1, c.a2, c.a3, c.a4, c.a5, c.a6, c.subtext,
        c.inactive, c.a1, c.a2, c.a3, c.a4, c.a5, c.a6, c.text)
    local old = io.open(ALACRITTY, "r")
    local same = old and old:read("*a") == toml
    if old then old:close() end
    if same then return end
    local f = io.open(ALACRITTY, "w")
    if f then f:write(toml); f:close() end
end
write_alacritty(T)

-- Win + Alt + T: the next theme.
local function next_theme()
    local cur, nxt = read_current(), ORDER[1]
    for i, known in ipairs(ORDER) do if known == cur then nxt = ORDER[i % #ORDER + 1] end end
    local f = io.open(CURRENT, "w")
    if f then f:write(nxt, "\n"); f:close() end
    local t = load_theme(nxt)
    hl.dispatch(hl.dsp.exec_cmd("hyprctl reload"))
    if t then
        hl.dispatch(hl.dsp.exec_cmd(string.format('hyprctl notify -1 2500 "rgb(%s)" "Theme: %s"', t.c.accent:sub(2), t.name)))
    end
end

pcall(hl.unbind, "SUPER + ALT + T")
hl.bind("SUPER + ALT + T", next_theme, { description = "Next theme" })
